flowchart TD
    subgraph globalconfig
    GlobalConfig-->SelectedObjectsData
    GlobalConfig-->MusicLibrary
    GlobalConfig-->SoundEffectLibrary
    GlobalConfig-->HLoggerSettings
    GlobalConfig-->GameSettings
    GlobalConfig-->Clock
    end
    subgraph propertydrawer
    end
    subgraph assetmodificationprocessor
    AssetModificationProcessor-->DeleteEmptyFolders
    end
    subgraph assetpostprocessor
    AssetPostprocessor-->TextureImportProcessor
    end
    subgraph monobehaviour
    end
    subgraph odineditorwindow
    OdinEditorWindow-->ObjectExplorer
    OdinEditorWindow-->ExtractorEditor
    OdinEditorWindow-->FolderNavigationEditor
    OdinEditorWindow-->LoggerSettingsEditor
    OdinEditorWindow-->OpenAllEditors
    OdinEditorWindow-->SelectionHistoryEditor
    OdinEditorWindow-->SpriteRenamerEditor
    OdinEditorWindow-->TextureEditor
    OdinEditorWindow-->ToolsEditor
    end
    subgraph propertyattribute
    end
    subgraph attribute
    end
    subgraph scriptableobjectsingleton
    end
    subgraph singleton
    end
    subgraph combatunit
    CombatUnit-->FrogController
    CombatUnit-->GuardController
    CombatUnit-->PigController
    CombatUnit-->NPCUnit
    CombatUnit-->PunchUnit
    end
    subgraph serializedscriptableobject
    end
    subgraph frogattackbase
    FrogAttackBase-->JumpBase
    FrogAttackBase-->SpitBase
    FrogAttackBase-->TongueBase
    end
    subgraph jumpbase
    JumpBase-->JumpSlam
    JumpBase-->JumpToPosition
    end
    subgraph spitbase
    SpitBase-->PoisonMortar
    SpitBase-->SlimeMortar
    end
    subgraph tonguebase
    TongueBase-->PoisonTongue
    end
    subgraph istate
    IState-->FrogAttackState
    IState-->GuardAttackState
    IState-->PigAttackState
    IState-->EmptyState
    IState-->FleeState
    IState-->IdleState
    IState-->PatrolState
    end
    subgraph iobserver
    IObserver-->Observer
    end
    subgraph isubject
    ISubject-->Subject
    end
    subgraph steeringbehaviour
    SteeringBehaviour-->ObstacleAvoidanceBehaviour
    SteeringBehaviour-->SeekBehaviour
    end
    subgraph detector
    Detector-->ObstacleDetector
    Detector-->TargetDetector
    end
    subgraph playermovement
    PlayerMovement-->Controller
    end
    subgraph controller
    Controller-->Hank
    end
    subgraph scriptableobject
    ScriptableObject-->EntityData
    ScriptableObject-->CollectionPreset
    ScriptableObject-->ContainerDefinition
    ScriptableObject-->ShopDefinition
    ScriptableObject-->ConditionBase
    ScriptableObject-->DebugSettings
    ScriptableObject-->TrapData
    ScriptableObject-->WorldRegion
    ScriptableObject-->KeyTriggerType
    end
    subgraph serializedmonobehaviour
    end
    subgraph unit
    Unit-->AnimatedUnit
    Unit-->StaticNPCUnit
    Unit-->UnitController
    end
    subgraph sprintunit
    SprintUnit-->BlockUnit
    end
    subgraph hurtunit
    HurtUnit-->CombatUnit
    end
    subgraph moveunit
    MoveUnit-->HurtUnit
    end
    subgraph animatedunit
    AnimatedUnit-->MoveUnit
    end
    subgraph playerunit
    PlayerUnit-->PlayerItems
    end
    subgraph playeritems
    PlayerItems-->PlayerMovement
    end
    subgraph blockunit
    BlockUnit-->PlayerUnit
    end
    subgraph punchunit
    PunchUnit-->SprintUnit
    end
    subgraph globalconfigcollection
    GlobalConfigCollection-->ItemCollection
    GlobalConfigCollection-->QuestCollection
    GlobalConfigCollection-->StatusEffectCollection
    GlobalConfigCollection-->UnitCollection
    end
    subgraph image
    Image-->CutoutMaskUI
    end
    subgraph debugcommandbase
    DebugCommandBase-->DebugCommand
    end
    subgraph icommand
    ICommand-->AIInput
    ICommand-->PlayerInput
    ICommand-->BlockCommand
    end
    subgraph observer
    Observer-->HurtObserver
    Observer-->MoveObserver
    Observer-->ObserverCommand
    Observer-->DialogueObserver
    Observer-->InstantObserver
    Observer-->ItemHeldObserver
    Observer-->ItemUsedObserver
    Observer-->KillObserver
    Observer-->RegionObserver
    Observer-->SpeakObserver
    Observer-->TriggerableObserver
    end
    subgraph ianimation
    IAnimation-->Animation
    end
    subgraph animatorbase
    AnimatorBase-->Animator
    AnimatorBase-->SpriteEffect
    end
    subgraph iattack
    IAttack-->Attack
    end
    subgraph attack
    Attack-->Punch
    Attack-->Spell
    end
    subgraph icommandfactory
    ICommandFactory-->CommandFactory
    end
    subgraph imediator
    IMediator-->ConcreteMediator
    end
    subgraph ienumerable
    IEnumerable-->CollectionInstance
    end
    subgraph unlockablebase
    UnlockableBase-->ContainerObject
    UnlockableBase-->Door
    UnlockableBase-->Trap
    end
    subgraph lightbase
    LightBase-->LightFire
    LightBase-->Luminousity
    LightBase-->Sun
    end
    subgraph triggerable
    Triggerable-->QuestLine
    Triggerable-->QuestPart
    end
    subgraph iquestcondition
    IQuestCondition-->ConditionTimeInterval
    end
    subgraph conditionbase
    ConditionBase-->ConditionTimer
    end
    subgraph publisher
    Publisher-->AnimatorBase
    end
    subgraph material
    Material-->SpriteGlowMaterial
    end
    subgraph isort
    ISort-->DynamicYSort
    ISort-->StaticYSort
    end
    subgraph worldtextbase
    WorldTextBase-->FloatingDamageNumber
    end
    subgraph effectbase
    EffectBase-->BerserkerEffect
    EffectBase-->BleedEffect
    EffectBase-->BurnEffect
    EffectBase-->HealthRegenEffect
    EffectBase-->HighEffect
    EffectBase-->LuminiousEffect
    EffectBase-->PoisonEffect
    EffectBase-->RecoveryEffect
    EffectBase-->ShockedEffect
    EffectBase-->SlowEffect
    EffectBase-->StaminaRegenerateEffect
    EffectBase-->StunEffect
    EffectBase-->WeakenedEffect
    EffectBase-->WetEffect
    end
    subgraph idisposable
    IDisposable-->EffectBase
    end
    subgraph subscribableeventbase
    SubscribableEventBase-->SubscribableEvent
    end
    subgraph iequatable
    IEquatable-->Orientation
    end
    subgraph tickbase
    TickBase-->TimeTick
    TickBase-->ValueTick
    end
    subgraph lockbase
    LockBase-->LockEvent
    LockBase-->LockItem
    LockBase-->LockLever
    end
    subgraph module
    Module-->AnimationModule
    Module-->BlockModule
    Module-->CombatModule
    Module-->HealthModule
    Module-->HurtModule
    Module-->InputModule
    Module-->MoveModule
    Module-->PunchModule
    Module-->SprintModule
    Module-->StaminaModule
    end
    subgraph unitcontroller
    UnitController-->DarkHank
    end
    subgraph ihank
    IHank-->_Hank
    end
