classDiagram
GlobalConfig --> Clock
GlobalConfig --> GameSettings
GlobalConfig --> HLoggerSettings
GlobalConfig --> MusicLibrary
GlobalConfig --> SelectedObjectsData
GlobalConfig --> SoundEffectLibrary
AssetModificationProcessor --|> DeleteEmptyFolders
AssetPostprocessor --|> TextureImportProcessor
CombatUnit --> FrogController
CombatUnit --> GuardController
CombatUnit --> NPCUnit
CombatUnit --> PigController
CombatUnit --> PunchUnit
FrogAttackBase --> JumpBase
FrogAttackBase --> SpitBase
FrogAttackBase --> TongueBase
JumpBase --> JumpSlam
JumpBase --> JumpToPosition
SpitBase --> PoisonMortar
SpitBase --> SlimeMortar
TongueBase --|> PoisonTongue
IState --> EmptyState
IState --> FleeState
IState --> FrogAttackState
IState --> GuardAttackState
IState --> IdleState
IState --> PatrolState
IState --> PigAttackState
IObserver --|> Observer
ISubject --|> Subject
SteeringBehaviour --> ObstacleAvoidanceBehaviour
SteeringBehaviour --> SeekBehaviour
Detector --> ObstacleDetector
Detector --> TargetDetector
PlayerMovement --|> Controller
Controller --|> Hank
Unit --> AnimatedUnit
Unit --> StaticNPCUnit
Unit --> UnitController
SprintUnit --|> BlockUnit
HurtUnit --|> CombatUnit
MoveUnit --|> HurtUnit
AnimatedUnit --|> MoveUnit
PlayerUnit --|> PlayerItems
PlayerItems --|> PlayerMovement
BlockUnit --|> PlayerUnit
PunchUnit --|> SprintUnit
GlobalConfigCollection --> ItemCollection
GlobalConfigCollection --> QuestCollection
GlobalConfigCollection --> StatusEffectCollection
GlobalConfigCollection --> UnitCollection
Image --|> CutoutMaskUI
DebugCommandBase --|> DebugCommand
ICommand --> AIInput
ICommand --> BlockCommand
ICommand --> PlayerInput
Observer --> DialogueObserver
Observer --> HurtObserver
Observer --> InstantObserver
Observer --> ItemHeldObserver
Observer --> ItemUsedObserver
Observer --> KillObserver
Observer --> MoveObserver
Observer --> ObserverCommand
Observer --> RegionObserver
Observer --> SpeakObserver
Observer --> TriggerableObserver
IAnimation --|> Animation
AnimatorBase --> Animator
AnimatorBase --> SpriteEffect
IAttack --|> Attack
Attack --> Punch
Attack --> Spell
ICommandFactory --|> CommandFactory
IMediator --|> ConcreteMediator
IEnumerable --|> CollectionInstance
UnlockableBase --> ContainerObject
UnlockableBase --> Door
UnlockableBase --> Trap
LightBase --> LightFire
LightBase --> Luminousity
LightBase --> Sun
Triggerable --> QuestLine
Triggerable --> QuestPart
IQuestCondition --|> ConditionTimeInterval
ConditionBase --|> ConditionTimer
Publisher --|> AnimatorBase
Material --|> SpriteGlowMaterial
ISort --> DynamicYSort
ISort --> StaticYSort
WorldTextBase --|> FloatingDamageNumber
EffectBase --> BerserkerEffect
EffectBase --> BleedEffect
EffectBase --> BurnEffect
EffectBase --> HealthRegenEffect
EffectBase --> HighEffect
EffectBase --> LuminiousEffect
EffectBase --> PoisonEffect
EffectBase --> RecoveryEffect
EffectBase --> ShockedEffect
EffectBase --> SlowEffect
EffectBase --> StaminaRegenerateEffect
EffectBase --> StunEffect
EffectBase --> WeakenedEffect
EffectBase --> WetEffect
IDisposable --|> EffectBase
SubscribableEventBase --|> SubscribableEvent
IEquatable --|> Orientation
TickBase --> TimeTick
TickBase --> ValueTick
LockBase --> LockEvent
LockBase --> LockItem
LockBase --> LockLever
Module --> AnimationModule
Module --> BlockModule
Module --> CombatModule
Module --> HealthModule
Module --> HurtModule
Module --> InputModule
Module --> MoveModule
Module --> PunchModule
Module --> SprintModule
Module --> StaminaModule
UnitController --|> DarkHank
IHank --|> _Hank
