flowchart LR
subgraph Editor
  AssemblyInfo
end
subgraph Editor_Data
  SelectedObjectsData
end
subgraph Editor_Drawers
  ObjectPoolEditor
  SerializableDictionaryDrawer
end
subgraph Editor_InitializeOnLoad
  CompilerOptionsEditorScript
  ScriptExecutionOrder
  ScriptOptions
  SelectionHistoryPersistent
end
subgraph Editor_Processors
  DeleteEmptyFolders
  TextureImportProcessor
end
subgraph Editor_Utils
  HClick
  InkEditorUtils
  MetaFixer
  ObjectExplorer
  QuickOpener
end
subgraph Editor_Window
  CharacterCreatorEditor
  ExtractorEditor
  FolderNavigationEditor
  LoggerSettingsEditor
  OpenAllEditors
  SelectionHistoryEditor
  SpriteRenameEditor
  TextureEditor
  ToolsEditor
end
subgraph Runtime
  AssemblyInfo
end
subgraph Runtime_Attributes
  MinMaxRangeAttribute
  ScriptExecutionOrder
  SerializableDictionary
end
subgraph Runtime_Audio
  AudioPoint
  EntitySFX
  FadeMixerGroup
  PlayWithVolume
  UnitSFX
end
subgraph Runtime_Audio_Cache
  MusicLibrary
  SoundEffectLibrary
  SoundUILibrary
end
subgraph Runtime_Cameras
  CameraFollow
  CameraSetup
end
subgraph Runtime_Character_AI_Firefly
  FireflyController
  FireflySpawner
end
subgraph Runtime_Character_AI_Frog
  FrogController
end
subgraph Runtime_Character_AI_Frog_Attacks
  FrogAttackBase
end
subgraph Runtime_Character_AI_Frog_Attacks_Jump
  JumpBase
  JumpSlam
  JumpToPosition
end
subgraph Runtime_Character_AI_Frog_Attacks_Spit
  PoisonMortar
  SlimeMortar
  SpitBase
  SpitProjectile
end
subgraph Runtime_Character_AI_Frog_Attacks_Tongue
  PoisonTongue
  TongueBase
end
subgraph Runtime_Character_AI_Frog_Colliders
  FrogDamageCollider
  FrogShockwave
end
subgraph Runtime_Character_AI_Frog_States
  FrogAttackState
end
subgraph Runtime_Character_AI_Guard
  GuardAttackState
  GuardController
end
subgraph Runtime_Character_AI_Pig
  PigAttackState
  PigController
end
subgraph Runtime_Character_AI_SM
  EmptyState
  FleeState
  IdleState
  IState
  PatrolState
  StateMachine
end
subgraph Runtime_Character_Modules
  IInteract
end
subgraph Runtime_Character_Modules_ObserverPattern
  IObserver
  ISubject
  Observer
  Subject
end
subgraph Runtime_Character_Modules_Steering
  AIData
  ContextSolver
  Detector
  EnemyAI
  ObstacleAvoidanceBehaviour
  ObstacleDetector
  SeekBehaviour
  SteeringBehaviour
  TargetDetector
end
subgraph Runtime_Character_Player
  Controller
  Hank
end
subgraph Runtime_Character_Steering
  AIData
  ContextSolver
  Detector
  Directions
  EnemyAI
  ObstacleAvoidanceBehaviour
  ObstacleDetector
  SeekBehaviour
  SteeringBehaviour
  TargetDetector
end
subgraph Runtime_Character_Units
  EntityData
  TrackedPositionData
  Unit
end
subgraph Runtime_Character_Units_Animated
  AnimatedUnit
end
subgraph Runtime_Character_Units_Block
  BlockUnit
end
subgraph Runtime_Character_Units_Combat
  Attack
  CombatUnit
  Throw
end
subgraph Runtime_Character_Units_Hurt
  HurtUnit
  StatusEffectModule
end
subgraph Runtime_Character_Units_Movement
  MoveUnit
end
subgraph Runtime_Character_Units_NPC
  NPCUnit
  StaticNPCUnit
end
subgraph Runtime_Character_Units_Player
  PlayerInteract
  PlayerItems
  PlayerMovement
  PlayerUnit
end
subgraph Runtime_Character_Units_Punch
  PunchUnit
end
subgraph Runtime_Character_Units_Sprint
  SprintUnit
end
subgraph Runtime_Collections
  GlobalConfigCollection
  HLoggerSettings
  ItemCollection
  QuestCollection
  StatusEffectCollection
  UnitCollection
end
subgraph Runtime_Enums
  AnimationType
  AttackType
  ContractType
  DestructionMethod
  GroundTile
  IdleMode
  ItemCollectionType
  LockStateType
  LockThreeWay
  MenuTabType
  NotebookCategory
  PageType
  QuestState
  SignalType
  StaminaTypes
  TabNavigationType
  ToggleType
  WorldKeyType
end
subgraph Runtime_Extensions
  CollectionsExtension
  ColorExtension
  ComponentExtension
  CoroutineExtension
  EnumExtension
  GameObjectExtension
  GenericExtensions
  MonoBehaviourExtensions
  NumberExtension
  RectExtension
  Rigidbody2DExtension
  SerializationExtension
  SpriteExtension
  SpriteRendererExtensions
  StringExtension
  Texture2DExtension
  TilemapExtension
  TransformExtension
  UnitExtensions
  Vector2Extension
end
subgraph Runtime_GameUI_Dialogue
  DialogueAnimator
  DialogueChoiceButton
  DialogueHandler
  DialoguePortrait
  DialogueSoundHandler
  DialogueTextBubble
  DialogueTimer
  MonologueColliderEvent
end
subgraph Runtime_GameUI_Dialogue_Helpers
  DialogueGlobals
  DialogueLockUnlocker
  DialogueTags
  DialogueTriggerLockUnlocker
  DialogueVariables
end
subgraph Runtime_GameUI_Events
  GameEvents
  GuiEvents
end
subgraph Runtime_GameUI_GameMenu
  BossPanel
  GameNotice
  PortraitDamageUI
  QuestTracker
  RegionTextNotice
  StatusEffectIcon
  StatusEffectUI
  TabNavigation
  UIGameMenuItems
end
subgraph Runtime_GameUI_Input
  GamepadIcons
  InputActionUI
  InputUISpawner
  InteractFollower
end
subgraph Runtime_GameUI_Inventory
  CoinDisplayUI
  ContainerUI
  DisplayItemPopupUI
  InventoryHandler
  ItemDetailsUI
  ItemSlotUI
  ItemUI
  SelectorUI
end
subgraph Runtime_GameUI_Journal
  ImageObjectSettings
  JournalHandler
  PageCollection
  PagePairUI
  SinglePageUI
  TextObjectSettings
end
subgraph Runtime_GameUI_MainMenu
  MainMenuHandler
  MenuHandAnimator
  MenuLoadProgress
  ParallaxScrolling
end
subgraph Runtime_GameUI_Popup
  PopupPanelUI
  TextPopup
  TextPopupHandlerUI
end
subgraph Runtime_GameUI_Tooltip
  Tooltip
  TooltipUI
end
subgraph Runtime_GameUI_TransitionEffects
  CutoutAnimation
  CutoutMaskUI
end
subgraph Runtime_HDebug
  HExtractor
  HLogger
end
subgraph Runtime_HDebug_Console
  ConsoleController
  DebugCommandBase
end
subgraph Runtime_HDebug_Display
  ConsoleToGUI
end
subgraph Runtime_Interfaces
  Execution
  IDelayed
  IRequirement
end
subgraph Runtime_Interfaces_Inputs
  AIInput
  PlayerInput
end
subgraph Runtime_Interfaces_Listeners
  BlockCommand
  HurtObserver
  MoveObserver
  ObserverCommand
end
subgraph Runtime_Interfaces_Modules
  IOrientation
end
subgraph Runtime_Interfaces_Modules_Animation
  Animation
  Animator
  IAnimation
  IAnimator
end
subgraph Runtime_Interfaces_Modules_Interaction
  IDialogue
  IInteract
end
subgraph Runtime_Interfaces_Modules_Movement
  IMove
  IMoveDirectional
  IMovementModule
  IMovePathfinding
  MovementModule
end
subgraph Runtime_Interfaces_Modules_Physical
  Attack
  IAttack
  IAttacker
  IBlock
  IHurt
  IPunch
  Punch
  Spell
end
subgraph Runtime_Interfaces_Patterns_Commands
  CommandFactory
  ICommand
  ICommandFactory
end
subgraph Runtime_Interfaces_Patterns_Mediation
  BaseComponent
  ConcreteMediator
  IMediator
  Mediator
end
subgraph Runtime_Interfaces_Patterns_Observe
  IObserver
  ISubject
  Observer
  Publisher
end
subgraph Runtime_Inventory_Main
  CollectionInstance
  CollectionPreset
  ContainerDefinition
  LockState
  ShopDefinition
end
subgraph Runtime_Inventory_WorldObjects
  ContainerObject
  ShopObject
end
subgraph Runtime_Items
  Item
  ItemConsumeAttribute
  ItemObject
  ItemObjectGroup
  ItemThrowAttribute
  Rarity
  UsageType
end
subgraph Runtime_Lightning
  LightBase
  LightFire
  Luminousity
  Sun
end
subgraph Runtime_Managers
  ClockManager
  FMODManager
  InputManager
  QuestManager
  RegionManager
  SaveSettings
  VideoManager
end
subgraph Runtime_Menu
  MainMenuUI
end
subgraph Runtime_Quest
  BadTrigger
  Note
  QuestLine
  QuestPart
  Trigger
  Triggerable
  TriggerGroup
end
subgraph Runtime_Quest_Conditions
  ConditionBase
  ConditionTimeInterval
  ConditionTimer
end
subgraph Runtime_Quest_Enums
  InkValueTypes
  NumberComparer
  NumberComparerSource
  TriggerableState
  TriggerTypes
end
subgraph Runtime_Quest_Observers
  DialogueObserver
  InstantObserver
  ItemHeldObserver
  ItemUsedObserver
  KillObserver
  Observer
  RegionObserver
  SpeakObserver
  TriggerableObserver
end
subgraph Runtime_Rendering
  AnimatorBase
  SpriteEffect
end
subgraph Runtime_Rendering_Gizmos
  ColliderGizmo
  GizmosDebug
end
subgraph Runtime_Rendering_Glow
  GlowColorRandomizer
  SpriteGlowEffect
  SpriteGlowMaterial
end
subgraph Runtime_Rendering_ShaderEffects
  Rain
end
subgraph Runtime_Rendering_Sorting
  DynamicYSort
  ISort
  StaticYSort
end
subgraph Runtime_Rendering_Text
  FloatingDamageNumber
  TextDisplay
  WorldTextBase
end
subgraph Runtime_Settings
  DebugSettings
  GameSettings
  PlayerControls
end
subgraph Runtime_StatusEffects_Effects
  BerserkerEffect
  BleedEffect
  BurnEffect
  HealthRegenEffect
  HighEffect
  LuminiousEffect
  PoisonEffect
  RecoveryEffect
  ShockedEffect
  SlowEffect
  StaminaRegenerateEffect
  StunEffect
  WeakenedEffect
  WetEffect
end
subgraph Runtime_StatusEffects_Models
  EffectBase
  EntityState
  StatusType
end
subgraph Runtime_Utilities
  ActivateOnStart
  CollisionTrigger
  ComponentUtils
  DestroyAfter
  DisableOnStart
  GraphicUtility
  LayerMaskBuilder
  MaskUtils
  ObjectPool
  ObjectUtils
  ResourceUtility
  SceneUtility
  SubscribableEvent
  TypeHelpers
  VectorUtils
end
subgraph Runtime_Utilities_Singletons
  ScriptableObjectSingleton
  Singleton
  SingletonPerLevel
end
subgraph Runtime_Utilities_Stats
  StatModifier
  ValueStat
end
subgraph Runtime_Utilities_Tickers
  DelayAction
  DelayTicker
  FixedTimer
  TickBase
  TimeTick
  ValueTick
end
subgraph Runtime_World
  Delevation
  DigZone
  Elevation
  Punchable
end
subgraph Runtime_World_Doodads
  Bush
end
subgraph Runtime_World_GameClock
  Clock
  GameClockData
  SeasonStates
  TimeState
end
subgraph Runtime_World_House
  HouseCamera
  HouseDoor
  HouseTeleportTrigger
end
subgraph Runtime_World_Interactables
  ShroomExplosion
end
subgraph Runtime_World_LockKey
  Door
  DoorData
  KeyControlGroup
  Lever
  LockBase
  LockEvent
  LockItem
  LockLever
  PressurePlate
  UnlockableBase
  WorldKey
end
subgraph Runtime_World_LockKey_Trap
  Trap
  TrapData
end
subgraph Runtime_World_Region
  RegionTriggerData
  WorldRegion
end
subgraph Runtime_World_Triggers
  ForestTeleportTrigger
  LayerTrigger
  RegionTrigger
  TriggerCollider
end
subgraph Runtime_World_Triggers_KeyTrigger
  KeyTrigger
  KeyTriggerType
end
subgraph Runtime__Application
  Init
  Main
  UI
  Visualization
end
subgraph Runtime__New_DarkHank
  AnimationModule
  AttackData
  BlockModule
  CombatModule
  DarkHank
  HealthModule
  HurtModule
  InputModule
  Module
  MoveModule
  PunchModule
  SprintModule
  StaminaModule
  UnitController
end
subgraph Runtime__New_Data
  IUnit
  PositionData
  Unit
end
SelectedObjectsData --> GlobalConfig
ObjectPoolEditor --> PropertyDrawer
SerializableDictionaryDrawer --> PropertyDrawer
DeleteEmptyFolders --> AssetModificationProcessor
TextureImportProcessor --> AssetPostprocessor
HClick --> MonoBehaviour
ObjectExplorer --> OdinEditorWindow
ExtractorEditor --> OdinEditorWindow
FolderNavigationEditor --> OdinEditorWindow
LoggerSettingsEditor --> OdinEditorWindow
OpenAllEditors --> OdinEditorWindow
SelectionHistoryEditor --> OdinEditorWindow
SpriteRenameEditor --> OdinEditorWindow
TextureEditor --> OdinEditorWindow
ToolsEditor --> OdinEditorWindow
MinMaxRangeAttribute --> PropertyAttribute
MinMaxRangeAttribute --> PropertyDrawer
ScriptExecutionOrder --> Attribute
AudioPoint --> MonoBehaviour
EntitySFX --> MonoBehaviour
UnitSFX --> MonoBehaviour
MusicLibrary --> GlobalConfig
SoundEffectLibrary --> GlobalConfig
SoundUILibrary --> ScriptableObjectSingleton
CameraFollow --> Singleton
CameraSetup --> MonoBehaviour
FireflyController --> MonoBehaviour
FireflySpawner --> MonoBehaviour
FrogController --> CombatUnit
FrogAttackBase --> SerializedScriptableObject
JumpBase --> FrogAttackBase
JumpSlam --> JumpBase
JumpToPosition --> JumpBase
PoisonMortar --> SpitBase
SlimeMortar --> SpitBase
SpitBase --> FrogAttackBase
SpitProjectile --> SerializedScriptableObject
PoisonTongue --> TongueBase
TongueBase --> FrogAttackBase
FrogDamageCollider --> MonoBehaviour
FrogShockwave --> MonoBehaviour
FrogAttackState --> IState
GuardAttackState --> IState
GuardController --> CombatUnit
PigAttackState --> IState
PigController --> CombatUnit
EmptyState --> IState
FleeState --> IState
IdleState --> IState
PatrolState --> IState
Observer --> IObserver
Subject --> ISubject
AIData --> MonoBehaviour
ContextSolver --> MonoBehaviour
Detector --> MonoBehaviour
EnemyAI --> MonoBehaviour
ObstacleAvoidanceBehaviour --> SteeringBehaviour
ObstacleDetector --> Detector
SeekBehaviour --> SteeringBehaviour
SteeringBehaviour --> MonoBehaviour
TargetDetector --> Detector
Controller --> PlayerMovement
Hank --> Controller
AIData --> MonoBehaviour
ContextSolver --> MonoBehaviour
Detector --> MonoBehaviour
EnemyAI --> MonoBehaviour
ObstacleAvoidanceBehaviour --> SteeringBehaviour
ObstacleDetector --> Detector
SeekBehaviour --> SteeringBehaviour
SteeringBehaviour --> MonoBehaviour
TargetDetector --> Detector
EntityData --> ScriptableObject
TrackedPositionData --> SerializedScriptableObject
Unit --> SerializedMonoBehaviour
AnimatedUnit --> Unit
BlockUnit --> SprintUnit
Attack --> SerializedScriptableObject
CombatUnit --> HurtUnit
Throw --> MonoBehaviour
HurtUnit --> MoveUnit
MoveUnit --> AnimatedUnit
NPCUnit --> CombatUnit
StaticNPCUnit --> Unit
PlayerInteract --> MonoBehaviour
PlayerItems --> PlayerUnit
PlayerMovement --> PlayerItems
PlayerUnit --> BlockUnit
PunchUnit --> CombatUnit
SprintUnit --> PunchUnit
HLoggerSettings --> GlobalConfig
ItemCollection --> GlobalConfigCollection
QuestCollection --> GlobalConfigCollection
StatusEffectCollection --> GlobalConfigCollection
UnitCollection --> GlobalConfigCollection
CoroutineExtension --> MonoBehaviour
DialogueAnimator --> MonoBehaviour
DialogueChoiceButton --> MonoBehaviour
DialogueHandler --> MonoBehaviour
DialoguePortrait --> MonoBehaviour
DialogueSoundHandler --> MonoBehaviour
DialogueTextBubble --> MonoBehaviour
DialogueTimer --> MonoBehaviour
MonologueColliderEvent --> MonoBehaviour
DialogueLockUnlocker --> MonoBehaviour
DialogueTriggerLockUnlocker --> MonoBehaviour
BossPanel --> MonoBehaviour
GameNotice --> MonoBehaviour
PortraitDamageUI --> MonoBehaviour
QuestTracker --> Singleton
RegionTextNotice --> MonoBehaviour
StatusEffectIcon --> MonoBehaviour
StatusEffectUI --> MonoBehaviour
TabNavigation --> Singleton
UIGameMenuItems --> MonoBehaviour
InputActionUI --> MonoBehaviour
InputUISpawner --> MonoBehaviour
InteractFollower --> MonoBehaviour
CoinDisplayUI --> MonoBehaviour
ContainerUI --> MonoBehaviour
DisplayItemPopupUI --> MonoBehaviour
InventoryHandler --> Singleton
ItemDetailsUI --> MonoBehaviour
ItemSlotUI --> MonoBehaviour
ItemUI --> MonoBehaviour
SelectorUI --> MonoBehaviour
JournalHandler --> Singleton
PagePairUI --> MonoBehaviour
SinglePageUI --> MonoBehaviour
MainMenuHandler --> MonoBehaviour
MenuHandAnimator --> MonoBehaviour
MenuLoadProgress --> Singleton
ParallaxScrolling --> MonoBehaviour
PopupPanelUI --> MonoBehaviour
TextPopup --> MonoBehaviour
TextPopupHandlerUI --> MonoBehaviour
Tooltip --> MonoBehaviour
TooltipUI --> MonoBehaviour
CutoutAnimation --> MonoBehaviour
CutoutMaskUI --> Image
HLogger --> MonoBehaviour
ConsoleController --> Singleton
DebugCommandBase --> DebugCommandBase
ConsoleToGUI --> MonoBehaviour
AIInput --> ICommand
PlayerInput --> ICommand
BlockCommand --> ICommand
HurtObserver --> Observer
MoveObserver --> Observer
ObserverCommand --> Observer
Animation --> IAnimation
Animator --> AnimatorBase
MovementModule --> MonoBehaviour
Attack --> IAttack
Punch --> Attack
Spell --> Attack
CommandFactory --> ICommandFactory
ConcreteMediator --> IMediator
Observer --> IObserver
Publisher --> SerializedMonoBehaviour
CollectionInstance --> IEnumerable
CollectionPreset --> ScriptableObject
ContainerDefinition --> ScriptableObject
LockState --> SerializedScriptableObject
ShopDefinition --> ScriptableObject
ContainerObject --> UnlockableBase
ShopObject --> MonoBehaviour
Item --> SerializedScriptableObject
ItemObject --> MonoBehaviour
ItemObjectGroup --> MonoBehaviour
LightBase --> MonoBehaviour
LightFire --> LightBase
Luminousity --> LightBase
Sun --> LightBase
ClockManager --> Singleton
FMODManager --> Singleton
InputManager --> Singleton
QuestManager --> Singleton
RegionManager --> Singleton
VideoManager --> Singleton
MainMenuUI --> MonoBehaviour
QuestLine --> Triggerable
QuestPart --> Triggerable
Triggerable --> SerializedScriptableObject
ConditionBase --> ScriptableObject
ConditionTimeInterval --> IQuestCondition
ConditionTimer --> ConditionBase
DialogueObserver --> Observer
InstantObserver --> Observer
ItemHeldObserver --> Observer
ItemUsedObserver --> Observer
KillObserver --> Observer
RegionObserver --> Observer
SpeakObserver --> Observer
TriggerableObserver --> Observer
AnimatorBase --> Publisher
SpriteEffect --> AnimatorBase
ColliderGizmo --> MonoBehaviour
GlowColorRandomizer --> MonoBehaviour
SpriteGlowEffect --> MonoBehaviour
SpriteGlowMaterial --> Material
Rain --> MonoBehaviour
DynamicYSort --> ISort
ISort --> MonoBehaviour
StaticYSort --> ISort
FloatingDamageNumber --> WorldTextBase
TextDisplay --> MonoBehaviour
WorldTextBase --> MonoBehaviour
DebugSettings --> ScriptableObject
GameSettings --> GlobalConfig
BerserkerEffect --> EffectBase
BleedEffect --> EffectBase
BurnEffect --> EffectBase
HealthRegenEffect --> EffectBase
HighEffect --> EffectBase
LuminiousEffect --> EffectBase
PoisonEffect --> EffectBase
RecoveryEffect --> EffectBase
ShockedEffect --> EffectBase
SlowEffect --> EffectBase
StaminaRegenerateEffect --> EffectBase
StunEffect --> EffectBase
WeakenedEffect --> EffectBase
WetEffect --> EffectBase
EffectBase --> IDisposable
ActivateOnStart --> MonoBehaviour
CollisionTrigger --> MonoBehaviour
DestroyAfter --> MonoBehaviour
DisableOnStart --> MonoBehaviour
SubscribableEvent --> SubscribableEventBase
VectorUtils --> IEquatable
Singleton --> Singleton
DelayTicker --> Singleton
TimeTick --> TickBase
ValueTick --> TickBase
Delevation --> MonoBehaviour
DigZone --> MonoBehaviour
Elevation --> MonoBehaviour
Punchable --> MonoBehaviour
Bush --> MonoBehaviour
Clock --> GlobalConfig
HouseCamera --> MonoBehaviour
HouseDoor --> MonoBehaviour
HouseTeleportTrigger --> MonoBehaviour
ShroomExplosion --> MonoBehaviour
Door --> UnlockableBase
DoorData --> SerializedScriptableObject
KeyControlGroup --> MonoBehaviour
Lever --> MonoBehaviour
LockBase --> MonoBehaviour
LockEvent --> LockBase
LockItem --> LockBase
LockLever --> LockBase
PressurePlate --> MonoBehaviour
UnlockableBase --> MonoBehaviour
WorldKey --> MonoBehaviour
Trap --> UnlockableBase
TrapData --> ScriptableObject
WorldRegion --> ScriptableObject
ForestTeleportTrigger --> MonoBehaviour
LayerTrigger --> MonoBehaviour
RegionTrigger --> MonoBehaviour
TriggerCollider --> MonoBehaviour
KeyTrigger --> MonoBehaviour
KeyTriggerType --> ScriptableObject
Init --> MonoBehaviour
Main --> MonoBehaviour
UI --> Singleton
Visualization --> MonoBehaviour
AnimationModule --> Module
BlockModule --> Module
CombatModule --> Module
DarkHank --> UnitController
HealthModule --> Module
HurtModule --> Module
InputModule --> Module
Module --> SerializedMonoBehaviour
MoveModule --> Module
PunchModule --> Module
SprintModule --> Module
StaminaModule --> Module
UnitController --> Unit
IUnit --> IHank
PositionData --> SerializedScriptableObject
Unit --> SerializedMonoBehaviour