classDiagram
UnlockableBase --|> Trap
ScriptableObject --|> TrapData
ScriptableObject --|> WorldRegion
MonoBehaviour --|> ForestTeleportTrigger
MonoBehaviour --|> LayerTrigger
MonoBehaviour --|> RegionTrigger
MonoBehaviour --|> TriggerCollider
MonoBehaviour --|> KeyTrigger
ScriptableObject --|> KeyTriggerType
MonoBehaviour --|> Init
MonoBehaviour --|> Main
Singleton --|> UI
MonoBehaviour --|> Visualization
Module --|> AnimationModule
Module --|> BlockModule