classDiagram
MonoBehaviour --|> ShopObject
SerializedScriptableObject --|> Item
MonoBehaviour --|> ItemObject
MonoBehaviour --|> ItemObjectGroup
MonoBehaviour --|> LightBase
LightBase --|> LightFire
LightBase --|> Luminousity
LightBase --|> Sun
Singleton --|> ClockManager
Singleton --|> FMODManager
Singleton --|> InputManager
Singleton --|> QuestManager
Singleton --|> RegionManager
Singleton --|> VideoManager
MonoBehaviour --|> MainMenuUI